# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Feature-DEV' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftLint'
  pod "RxSwift"
  pod "RxCocoa"
  pod 'SnapKit'
  pod 'Toaster'
  pod 'Then'
  # Pods for Feature-DEV

end
